name: Electron Release

on:
  push:
    branches:
      - main

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

  # build-windows:
  #   needs: create-github-release

  build-macos:
    needs: create-github-release
    runs-on: macos-latest # Required for building macOS DMGs with dmg-license
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.18.0'

    - name: Install electron dependencies
      run: node -v && npm -v && npm install

    - name: Install cms-site dependencies
      run: cd cms-site && npm install

    - name: Build Electron app (macOS)
      run: npm run dist -- -m
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Release Asset (macOS x64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ needs.create-github-release.outputs.upload_url }}
        asset_path: ./dist/tables-cms-macos-x64.dmg
        asset_name: tables-cms-macos-x64.dmg
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (macOS arm64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ needs.create-github-release.outputs.upload_url }}
        asset_path: ./dist/tables-cms-macos-arm64.dmg
        asset_name: tables-cms-macos-arm64.dmg
        asset_content_type: application/octet-stream

  build-linux:
    needs: create-github-release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.18.0'

    - name: Install electron dependencies
      run: node -v && npm -v && npm install

    - name: Install cms-site dependencies
      run: cd cms-site && npm install

    - name: Build Electron app (Linux)
      run: npm run dist -- -l
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Release Asset (Linux)
      id: upload-linux-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ needs.create-github-release.outputs.upload_url }}
        asset_path: ./dist/tables-cms-linux.AppImage
        asset_name: tables-cms-linux.AppImage
        asset_content_type: application/octet-stream
